language: python
python:
  - "3.6"
install:
  - pip install pytest pytest-cov
  - pip install coveralls
  - pip install -r requirements.txt
script:
  - PYTHONPATH=. py.test --cov=./src/main ./src/test
after_success:
  - coveralls
